jobs:
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - powershell: .\build\build.ps1 -script build\build.cake
    displayName: Build 

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: ' $(build.sourcesdirectory)\build\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: unosourcegenerator-drop
      ArtifactType: Container

- job: Linux

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - bash: msbuild /r /p:Configuration=Release /p:AddSyntheticProjectReferencesForSolutionDependencies=false ./src/Uno.SourceGenerator.Linux.sln
    displayName: Build

- job: macOS

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - bash: msbuild /r /p:Configuration=Release /p:AddSyntheticProjectReferencesForSolutionDependencies=false ./src/Uno.SourceGenerator.Linux.sln
    displayName: Build
