<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
  </PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Uno.SourceGenerationTasks" Version="3.0.0-dev.*" />
	</ItemGroup>

	<Import Project="..\MyGenerator\build\MyGenerator.props" />

</Project>
